<LoadingPopup>:
    auto_dismiss: False
    size_hint: None, None
    size: 0, 0
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}

    canvas.before:
        PushMatrix
        Rotate:
            angle: root.angle
            axis: 0, 0, 1
            origin: root.center

    canvas.after:
        PopMatrix


    Image:
        size_hint: None, None
        size: self.texture_size
        source: 'data/images/icon.png'