<Widget>:
    font_name: 'fonts/Roboto-BoldItalic'


<ShadeButton>:


<BlueButton>:
    background_normal: ''
    background_color: 0, .2, .5, 1


<FontelloButton>:
    font_name: 'fonts/fontello.ttf'
    font_size: '25sp'


<ColoredScreen>:
    canvas.before:
        # Color: 
            # rgba: .85, .66, .01, 1
        Rectangle:
            source: 'data/images/background.jpg'
            pos: self.pos
            size: self.size
